### ISSUE TITLE
Sprites, characters and backgrounds

### ISSUE THREAD

**Issue by neil9669** [neil9669/eggStremely#3]
Dario is working on gathering the sprites, characters and backgrounds. We will also require people to work on the readme and the game itself. If there is anything that you would prefer to do, you can put it in the thread.

**Comment by neil9669** [comment]
Dario is looking at this

**Comment by stephendawsondev** [comment]
Dario pushed his branch with the sprites for Grogu, the Mandalorian, the frog lady and the egg jar in PR #34.
I added the sprites to the egg jar and enemies in PR #36 .

**Comment by stephendawsondev** [comment]
@Darioc18 Well done on all of these! Everything looks great! I'll close off the issue as you've done all you can before the submission.
