### ISSUE TITLE
USER STORY: Pace / Timing of Game 

### ISSUE THREAD

**Issue by farah-maria** [neil9669/eggStremely#41]
As a **the player** I can **make rapid progress through the game with clear opportunities/ perks and enough obstacles** so that **the game stays interesting**.

**Comment by stephendawsondev** [comment]
The instructions will be provided on the splash screen. The game itself isn't too complicated, but we may also want to display a warning message when the second enemy is first introduced.

**Comment by stephendawsondev** [comment]
Tested:

- [ ] Speed of Grogu is fast enough to get eggs, but tactic needed to avoid enemies
- [ ] Scene restarts quickly so that the user can continue playing without delays
- [ ] Enemy speed increases so that the user faces more of a challenge
