### ISSUE TITLE
TICKET - Frog Lady & Mandelorian

### ISSUE THREAD

**Issue by farah-maria** [neil9669/eggStremely#9]
Code the beginnings of these characters and their functions using JavaScript for Kaboom. Both will have the same functions but will just look different.

**Comment by stephendawsondev** [comment]
- [ ] Create the spawnEnemy function in a separate file and export to main.js
- [ ] Spawn enemy on the screen using a placeholder until we have the sprite
- [ ] Add random movement to the enemies
- [ ] See how to increase speed of enemies based on the score
- [ ] See how to switch enemies' direction to target the player

**Comment by stephendawsondev** [comment]
We won't get to add the AI tracking of the character for the submissions, so I'm closing this off for now.
